// <auto-generated />
namespace Exercise2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class RemoveN2nRelationshipFromVideosAndGenresTables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RemoveN2nRelationshipFromVideosAndGenresTables));
        
        string IMigrationMetadata.Id
        {
            get { return "201901090621159_RemoveN2nRelationshipFromVideosAndGenresTables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
